export enum BasicInfoField {
  ID = "id",
  FIRSTNAME = "firstName",
  LASTNAME = "lastName",
  MAIDENNAME = "maidenName",
  AGE = "age",
  GENDER = "gender",
  EMAIL = "email",
  PHONE = "phone",
  USERNAME = "username",
  PASSWORD = "password",
  BIRTHDATE = "birthDate",
  IMAGE = "image",
  BLOODGROUP = "bloodGroup",
  HEIGHT = "height",
  WEIGHT = "weight",
  EYECOLOR = "eyeColor",
}